apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: secret
spec:
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  refreshInterval: 10m
  target:
    name: ENV
  dataFrom:
  - extract:
      key: "{{.Values.deployment.env}}-password" 
